# Generated by Django 4.0.2 on 2022-02-08 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='date',
            new_name='trasaction_date',
        ),
    ]
