# Generated by Django 4.0.2 on 2022-02-08 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_rename_date_file_trasaction_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='trasaction_date',
            new_name='transaction_date',
        ),
    ]
